In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import cifar10

(train_images, train_labels), (test_images, test_labels) = cifar10.load_data()

# 데이터 정규화
train_images = train_images.astype('float32') / 255.0
test_images = test_images.astype('float32') / 255.0

# train_images에서 학습 및 검증 데이터 분리
val_images = train_images[45000:]
val_labels = train_labels[45000:]

train_images = train_images[:45000]
train_labels = train_labels[:45000]


170498071/170498071 [==============================] - 2s 0us/step


In [2]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

# model1 정의
model1 = Sequential([
    Conv2D(2, (5,5), strides=1, padding='same', activation='relu', input_shape=(32,32,3)),
    MaxPooling2D(pool_size=(2,2), strides=(2,2), padding='same'),

    Conv2D(2, (3,3), strides=1, padding='same', activation='relu'),
    MaxPooling2D(pool_size=(2,2), strides=(2,2), padding='same'),

    Conv2D(2, (3,3), strides=1, padding='same', activation='relu'),
    MaxPooling2D(pool_size=(2,2), strides=(2,2), padding='same'),

    Flatten(),
    Dense(256, activation='relu'),
    Dense(128, activation='relu'),
    Dense(10) # FC2 층은 activation 함수 사용하지 않음
])

model1.compile(optimizer='adam', loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True), metrics=['accuracy'])
history1 = model1.fit(train_images, train_labels, epochs=10, batch_size=16, validation_data=(val_images, val_labels))

Epoch 1/10
2813/2813 [==============================] - 25s 5ms/step - loss: 1.8773 - accuracy: 0.3050 - val_loss: 1.7644 - val_accuracy: 0.3444
Epoch 2/10
2813/2813 [==============================] - 13s 5ms/step - loss: 1.7342 - accuracy: 0.3620 - val_loss: 1.6894 - val_accuracy: 0.3770
Epoch 3/10
2813/2813 [==============================] - 14s 5ms/step - loss: 1.6668 - accuracy: 0.3894 - val_loss: 1.6444 - val_accuracy: 0.4004
Epoch 4/10
2813/2813 [==============================] - 13s 5ms/step - loss: 1.6238 - accuracy: 0.4058 - val_loss: 1.5987 - val_accuracy: 0.4196
Epoch 5/10
2813/2813 [==============================] - 13s 5ms/step - loss: 1.5877 - accuracy: 0.4239 - val_loss: 1.5861 - val_accuracy: 0.4328
Epoch 6/10
2813/2813 [==============================] - 13s 5ms/step - loss: 1.5561 - accuracy: 0.4346 - val_loss: 1.5719 - val_accuracy: 0.4348
Epoch 7/10
2813/2813 [==============================] - 13s 5ms/step - loss: 1.5311 - accuracy: 0.4471 - val_loss: 1.5393 - val_ac

In [3]:
# model2 정의
model2 = Sequential([
    Conv2D(32, (5,5), strides=1, padding='same', activation='relu', input_shape=(32,32,3)),
    MaxPooling2D(pool_size=(2,2), strides=(2,2), padding='same'),

    Conv2D(24, (3,3), strides=1, padding='same', activation='relu'),
    MaxPooling2D(pool_size=(2,2), strides=(2,2), padding='same'),

    Conv2D(16, (3,3), strides=1, padding='same', activation='relu'),
    MaxPooling2D(pool_size=(2,2), strides=(2,2), padding='same'),

    Flatten(),
    Dense(256, activation='relu'),
    Dense(128, activation='relu'),
    Dense(10) # FC2 층은 activation 함수 사용하지 않음
])

model2.compile(optimizer='adam', loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True), metrics=['accuracy'])
history2 = model2.fit(train_images, train_labels, epochs=10, batch_size=16, validation_data=(val_images, val_labels))

Epoch 1/10
2813/2813 [==============================] - 16s 5ms/step - loss: 1.5531 - accuracy: 0.4352 - val_loss: 1.2631 - val_accuracy: 0.5346
Epoch 2/10
2813/2813 [==============================] - 13s 5ms/step - loss: 1.2338 - accuracy: 0.5583 - val_loss: 1.1892 - val_accuracy: 0.5658
Epoch 3/10
2813/2813 [==============================] - 13s 5ms/step - loss: 1.0844 - accuracy: 0.6151 - val_loss: 1.0789 - val_accuracy: 0.6122
Epoch 4/10
2813/2813 [==============================] - 14s 5ms/step - loss: 0.9836 - accuracy: 0.6530 - val_loss: 1.0197 - val_accuracy: 0.6364
Epoch 5/10
2813/2813 [==============================] - 13s 5ms/step - loss: 0.9029 - accuracy: 0.6801 - val_loss: 1.0327 - val_accuracy: 0.6482
Epoch 6/10
2813/2813 [==============================] - 13s 5ms/step - loss: 0.8400 - accuracy: 0.7020 - val_loss: 0.9522 - val_accuracy: 0.6756
Epoch 7/10
2813/2813 [==============================] - 14s 5ms/step - loss: 0.7795 - accuracy: 0.7235 - val_loss: 0.9802 - val_ac

In [4]:
# 모델 1 평가
test_loss1, test_acc1 = model1.evaluate(test_images, test_labels, verbose=2)
print("\nModel 1 Test accuracy:", test_acc1)

# 모델 2 평가
test_loss2, test_acc2 = model2.evaluate(test_images, test_labels, verbose=2)
print("\nModel 2 Test accuracy:", test_acc2)


313/313 - 1s - loss: 1.5226 - accuracy: 0.4512 - 1s/epoch - 3ms/step

Model 1 Test accuracy: 0.451200008392334
313/313 - 1s - loss: 1.0392 - accuracy: 0.6605 - 809ms/epoch - 3ms/step

Model 2 Test accuracy: 0.6604999899864197


In [5]:
import numpy as np

# Model 1 잘못 분류된 예제 찾기
predictions1 = model1.predict(test_images)
predicted_labels1 = np.argmax(predictions1, axis=1)
misclassified_idx1 = np.where(predicted_labels1 != test_labels.reshape(-1))[0]

# Model 2 잘못 분류된 예제 찾기
predictions2 = model2.predict(test_images)
predicted_labels2 = np.argmax(predictions2, axis=1)
misclassified_idx2 = np.where(predicted_labels2 != test_labels.reshape(-1))[0]

# Model 1 잘못 분류된 예제 번호 출력
print("\nMisclassified examples for Model 1:")
for i in range(0, len(misclassified_idx1), 10):
    print(misclassified_idx1[i:i+10])

# Model 2 잘못 분류된 예제 번호 출력
print("\nMisclassified examples for Model 2:")
for i in range(0, len(misclassified_idx2), 10):
    print(misclassified_idx2[i:i+10])

# 잘못 분류된 예제의 수 출력
print("\nNumber of misclassifications for Model 1:", len(misclassified_idx1))
print("Number of misclassifications for Model 2:", len(misclassified_idx2))

# 각 카테고리별 잘못 분류된 예제의 수 출력
categories = ["airplane", "automobile", "bird", "cat", "deer", "dog", "frog", "horse", "ship", "truck"]

misclassifications_per_category1 = np.zeros(10)
for idx in misclassified_idx1:
    misclassifications_per_category1[test_labels[idx][0]] += 1

print("\nModel 1: 각 범주의 분류오류 개수")
for i in range(10):
    print(f"({i}) {categories[i]}: {int(misclassifications_per_category1[i])} 개")

misclassifications_per_category2 = np.zeros(10)
for idx in misclassified_idx2:
    misclassifications_per_category2[test_labels[idx][0]] += 1

print("\nModel 2: 각 범주의 분류오류 개수")
for i in range(10):
    print(f"({i}) {categories[i]}: {int(misclassifications_per_category2[i])} 개")

313/313 [==============================] - 1s 2ms/step

Misclassified examples for Model 1:
[ 1  2  3  4  7  8 11 15 17 20]
[21 22 24 25 26 27 28 31 34 36]
[37 40 43 44 46 47 48 52 56 57]
[58 59 61 63 65 66 68 71 76 83]
[ 85  86  87  88  91  95  97  99 102 104]
[106 108 109 110 115 116 117 120 121 124]
[125 126 127 129 130 133 134 135 137 138]
[139 143 144 147 149 150 151 152 154 157]
[158 159 161 162 164 165 167 171 172 176]
[178 179 180 181 184 187 188 189 191 192]
[194 195 197 198 199 201 202 204 208 209]
[210 211 213 214 215 216 218 219 221 222]
[223 224 227 228 229 231 232 233 238 239]
[242 245 246 247 249 250 251 253 255 256]
[258 260 261 262 263 266 267 269 270 276]
[277 278 281 282 284 286 293 294 295 296]
[303 304 305 306 307 309 312 313 314 316]
[320 321 322 323 324 326 328 331 332 337]
[338 339 340 341 345 349 350 352 354 355]
[356 357 358 360 361 363 365 366 367 368]
[370 376 377 379 380 381 385 387 389 393]
[394 397 399 401 402 404 405 407 408 411]
[412 414 415 417 418 420